---
- name: os-specific vars
  include_vars: "{{ansible_os_family}}.yml"

- name: include java.yml
  include: java.yml
  when: logstash_java_install | bool
  tags:
      - java

- name: Include OS Specific setup tasks
  include: setup-{{ ansible_os_family }}.yml

- include: config.yml
- include: ssl.yml
- include: plugins.yml

- name: Ensure Logstash is started and enabled on boot.
  service:
    name: logstash
    state: started
    enabled: "{{ logstash_enabled_on_boot }}"
